[mypy]
# Mypy configuration settings

# Treats optional per-module flags as errors
disallow_untyped_defs = True
disallow_any_generics = False

# Type-checks the bodies of functions without type annotations
check_untyped_defs = True

# Allows variables to be inferred to subtypes of their declared types
strict_optional = True

# Disallows usage of Any as a type unless explicitly declared
warn_no_return = False
warn_redundant_casts = True
warn_unused_ignores = True

# Ignore untyped external dependencies
ignore_missing_imports = True

# Ignore all files in subdirectories of /tests
[mypy-tests.*]
ignore_errors = True

[mypy-chronicle.old_queue]
ignore_errors = True
